# workflow for testing the action.yml locally
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: ComposeDeploy
    steps:
      - uses: actions/checkout@v4
      - id: ComposeDeploy
        uses: lukasvdberk/compose-deploy-action@v4
        env:
          # API_KEY: ${{ secrets.API_KEY }}
          API_KEY: 'badmin' # TODO set this to your API key
        with:
          project-id: 'admin'
          docker-compose-file: 'example-docker-compose-project/docker-compose.yml'

